





```{r '{{analizyPOL[1,]$typ_szk2_skrot[[1]][[j]]}},b1setup', echo=FALSE, warning=FALSE, message=FALSE}

knitr::opts_chunk$set(
  echo=FALSE, warning=FALSE, message=FALSE, results='asis', fig.width = 10, fig.height = 10, fig.path = "figPOL/", out.width = "100%")
# wczytuję ramki danych z excela

# path = paste0("analizy_html/excele/", analizyPOL[1,]$nazwa_excel_B1[[1]][[{{j}}]])
# dane = read_excel_allsheets(path, TRUE)
# obiekt = data.frame(typ_szk2 = analizyPOL[1,]$typ_szk2[[1]][[{{j}}]],
#                     typ_szk2_dop2 = analizyPOL[1,]$typ_szk2_dop2[[1]][[{{j}}]])


set_flextable_defaults(
  font.family = "Cambria",
  font.size = 10,
  padding = 2,
  border.color = "#CCCCCC",
  line_spacing = 1.08,
  digits = 2,
  decimal.mark = ",",
  big.mark = " ",
  na_str = "<na>"
)
```


```{r '{{analizyPOL[1,]$typ_szk2_skrot[[1]][[j]]}},b1w1', fig.height=6, fig.width=10}

if (obiekt$typ_szk2 %in% "Branżowa szkoła I stopnia" |
    obiekt$typ_szk2 %in% "Młodociani w Branżowej szkole I stopnia" |
      obiekt$typ_szk2 %in% "Niemłodociani w Branżowej szkole I stopnia" ) {
cat0("### Bezrobocie rejestrowane  - absolwenci ", obiekt$typ_szk2_dop2," z  2022 r.  {-} \n\n")
}
if (obiekt$typ_szk2 %ni% c("Branżowa szkoła I stopnia", "Młodociani w Branżowej szkole I stopnia", "Niemłodociani w Branżowej szkole I stopnia")) {
cat0("## Bezrobocie rejestrowane  - absolwenci ", obiekt$typ_szk2_dop2," z  2022 r.  {-} \n\n")
}

    
cat0("Wykres ", wyk_num(), ": Poziom bezrobocia (odsetek zarejestrowanych) w poszczególnych miesiącach od lipca roku zakończenia nauki - absolwenci ", obiekt$typ_szk2_dop2, " z 2022 r. - ogółem\n\n")

(wykresBezrobocie %+%
    dane_wyk_B1_mscrok(pelna_finalna_ramka_wskaznikow, "Technikum", 2022)) |> # podmiana danych
  zmien_wielkosc_czcionek(baseSize = 16) |> # zmiana wielkości czcionki
  zmien_prog_pokazywania_etykiet(hideBelow = 0.04) |> # zmiana progu ukrywania etykiet
  zmien_rok_w_podpisie(2024)

```

```{r '{{analizyPOL[1,]$typ_szk2_skrot[[1]][[j]]}},b1t1'}

  cat0("Tabela ", tab_num(), ": Poziom bezrobocia (odsetek zarejestrowanych) w poszczególnych miesiącach od lipca roku zakończenia nauki - absolwenci ", obiekt$typ_szk2_dop2, " z 2022 r. - ogółem\n\n")
  
dane_tab_B1_mscrok(pelna_finalna_ramka_wskaznikow, "Technikum", 2022) %>%
  gentab_tab_D(2024)

```


```{r '{{analizyPOL[1,]$typ_szk2_skrot[[1]][[j]]}},B1w6', fig.height = 4}

cat0("Wykres ", wyk_num(), ": Poziom bezrobocia (odsetek zarejestrowanych) w grudniu 2022 r. - absolwenci ", obiekt$typ_szk2_dop2, " z 2022 r. - w podziale na płeć\n\n")

(wykresBezrobociePlec %+%
    dane_wyk_B1_plec(pelna_finalna_ramka_wskaznikow, "Technikum", 2022, 2022)) |> # podmiana danych
  zmien_wielkosc_czcionek(baseSize = 16) |> # zmiana wielkości czcionki
  zmien_prog_pokazywania_etykiet(hideBelow = 0.04) |> # zmiana progu ukrywania etykiet
  zmien_rok_w_podpisie(2024)   

```

```{r '{{analizyPOL[1,]$typ_szk2_skrot[[1]][[j]]}},B1t6'}

  cat0("Tabela ", tab_num(), ": Poziom bezrobocia (odsetek zarejestrowanych) w grudniu 2022 r. - absolwenci ", obiekt$typ_szk2_dop2, " z 2022 r. - w podziale na płeć\n\n")
 
dane_tab_B1_plec(pelna_finalna_ramka_wskaznikow, "Technikum", rok_absolwentow = 2022, rok = 2022) %>%
  gentab_tab_D(2024)
```


```{r '{{analizyPOL[1,]$typ_szk2_skrot[[1]][[j]]}},B1w7', fig.height = 4}

cat0("Wykres ", wyk_num(), ": Poziom bezrobocia (odsetek zarejestrowanych) w grudniu 2023 r. - absolwenci ", obiekt$typ_szk2_dop2, " z 2022 r. - w podziale na płeć\n\n")

(wykresBezrobociePlec %+%
    dane_wyk_B1_plec(pelna_finalna_ramka_wskaznikow, "Technikum", 2022, 2023)) |> # podmiana danych
  zmien_wielkosc_czcionek(baseSize = 16) |> # zmiana wielkości czcionki
  zmien_prog_pokazywania_etykiet(hideBelow = 0.04) |> # zmiana progu ukrywania etykiet
  zmien_rok_w_podpisie(2024)  

```

```{r '{{analizyPOL[1,]$typ_szk2_skrot[[1]][[j]]}},B1t7'}

  cat0("Tabela ", tab_num(), ": Poziom bezrobocia (odsetek zarejestrowanych) w grudniu 2023 r. - absolwenci ", obiekt$typ_szk2_dop2, " z 2022 r. - w podziale na płeć\n\n")
 
dane_tab_B1_plec(pelna_finalna_ramka_wskaznikow, "Technikum", rok_absolwentow = 2022, rok = 2022) %>%
  gentab_tab_D(2024)

```


```{r  '{{analizyPOL[1,]$typ_szk2_skrot[[1]][[j]]}},b1w3'}
if (obiekt$typ_szk2 %in% "Branżowa szkoła I stopnia" |
      obiekt$typ_szk2 %in% "Młodociani w Branżowej szkole I stopnia" |
      obiekt$typ_szk2 %in% "Niemłodociani w Branżowej szkole I stopnia" |
      obiekt$typ_szk2 %in% "Technikum" | obiekt$typ_szk2 %in% "Branżowa szkoła II stopnia" |
      obiekt$typ_szk2 %in% "Szkoła policealna") {

cat0("Wykres ", wyk_num(), ": Poziom bezrobocia (odsetek zarejestrowanych) w grudniu 2022 r. - absolwenci ", obiekt$typ_szk2_dop2, " z 2022 r. - w podziale na zawody o największej liczbie absolwentów\n\n")

(wykresBezrobocieZawod %+%
    dane_wyk_B1_zaw(pelna_finalna_ramka_wskaznikow, "Technikum", 2022, 2022)) |> # podmiana danych
  zmien_wielkosc_czcionek(baseSize = 16) |> # zmiana wielkości czcionki
  zmien_prog_pokazywania_etykiet(hideBelow = 0.04) |> # zmiana progu ukrywania etykiet
  zmien_rok_w_podpisie(2024)   
}
```

```{r '{{analizyPOL[1,]$typ_szk2_skrot[[1]][[j]]}},b1t3'}
if (obiekt$typ_szk2 %in% "Branżowa szkoła I stopnia" |
      obiekt$typ_szk2 %in% "Młodociani w Branżowej szkole I stopnia" |
      obiekt$typ_szk2 %in% "Niemłodociani w Branżowej szkole I stopnia" |
      obiekt$typ_szk2 %in% "Technikum" | obiekt$typ_szk2 %in% "Branżowa szkoła II stopnia" |
      obiekt$typ_szk2 %in% "Szkoła policealna") {

  cat0("Tabela ", tab_num(), ": Poziom bezrobocia (odsetek zarejestrowanych) w grudniu 2022 r. - absolwenci ", obiekt$typ_szk2_dop2, " z 2022 r. - w podziale na zawody o największej liczbie absolwentów\n\n")
 
dane_tab_B1_zaw(pelna_finalna_ramka_wskaznikow, "Technikum", rok_absolwentow = 2022, rok = 2023) %>%
  gentab_tab_D(2024)
}
```


```{r '{{analizyPOL[1,]$typ_szk2_skrot[[1]][[j]]}},b1w4'}
if (obiekt$typ_szk2 %in% "Branżowa szkoła I stopnia" |
      obiekt$typ_szk2 %in% "Młodociani w Branżowej szkole I stopnia" |
      obiekt$typ_szk2 %in% "Niemłodociani w Branżowej szkole I stopnia" |
      obiekt$typ_szk2 %in% "Technikum" | obiekt$typ_szk2 %in% "Branżowa szkoła II stopnia" |
      obiekt$typ_szk2 %in% "Szkoła policealna") {
cat0("Wykres ", wyk_num(), ": Poziom bezrobocia (odsetek zarejestrowanych) w grudniu 2023 r. - absolwenci ", obiekt$typ_szk2_dop2, " z 2022 r. - w podziale na zawody o największej liczbie absolwentów\n\n")

(wykresBezrobocieZawod %+%
    dane_wyk_B1_zaw(pelna_finalna_ramka_wskaznikow, "Technikum", 2022, 2023)) |> # podmiana danych
  zmien_wielkosc_czcionek(baseSize = 16) |> # zmiana wielkości czcionki
  zmien_prog_pokazywania_etykiet(hideBelow = 0.04) |> # zmiana progu ukrywania etykiet
  zmien_rok_w_podpisie(2024)   
}
```

```{r '{{analizyPOL[1,]$typ_szk2_skrot[[1]][[j]]}},b1t4'}
if (obiekt$typ_szk2 %in% "Branżowa szkoła I stopnia" |
      obiekt$typ_szk2 %in% "Młodociani w Branżowej szkole I stopnia" |
      obiekt$typ_szk2 %in% "Niemłodociani w Branżowej szkole I stopnia" |
      obiekt$typ_szk2 %in% "Technikum" | obiekt$typ_szk2 %in% "Branżowa szkoła II stopnia" |
      obiekt$typ_szk2 %in% "Szkoła policealna") {

  cat0("Tabela ", tab_num(), ": Poziom bezrobocia (odsetek zarejestrowanych) w grudniu 2023 r. - absolwenci ", obiekt$typ_szk2_dop2, " z 2022 r. - w podziale na zawody o największej liczbie absolwentów\n\n")
 
dane_tab_B1_zaw(pelna_finalna_ramka_wskaznikow, "Technikum", rok_absolwentow = 2022, rok = 2023) %>%
  gentab_tab_D(2024)
}  
```

