

<br>
<br>
<br>



```{r '{{analizyPOL[1,]$typ_szk2_skrot[[1]][[j]]}},d2setup', echo=FALSE, warning=FALSE, message=FALSE}

# wczytuję ramki danych z excela
knitr::opts_chunk$set(
  echo=FALSE, warning=FALSE, message=FALSE, results='asis', fig.width = 10, fig.height = 10, fig.path = "figPOL/", out.width = "100%")

# path = paste0("analizy_html/excele/", analizyPOL[1,]$nazwa_excel_d2[[1]][[{{j}}]])
# dane = read_excel_allsheets(path, TRUE)
# obiekt = data.frame(typ_szk2 = analizyPOL[1,]$typ_szk2[[1]][[{{j}}]],
#                     typ_szk2_dop2 = analizyPOL[1,]$typ_szk2_dop2[[1]][[{{j}}]])


set_flextable_defaults(
  font.family = "Cambria",
  font.size = 10,
  padding = 2,
  border.color = "#CCCCCC",
  line_spacing = 1.08,
  digits = 2,
  decimal.mark = ",",
  big.mark = " ",
  na_str = "<na>"
)
```


```{r '{{analizyPOL[1,]$typ_szk2_skrot[[1]][[j]]}},d2w3', fig.height=4, fig.width=10}
if (obiekt$typ_szk2 %in% "Szkoła policealna") {
    cat0("## Uzyskiwanie świadectwa dojrzałości - absolwenci ", obiekt$typ_szk2_dop2," z 2022 r. {-}  \n\n",
    
        "Absolwenci ", obiekt$typ_szk2_dop2," nie mogą zdobywać tego typu dyplomów.")
}
if (obiekt$typ_szk2 %in% "Branżowa szkoła I stopnia" |
      obiekt$typ_szk2 %in% "Młodociani w Branżowej szkole I stopnia" |
      obiekt$typ_szk2 %in% "Niemłodociani w Branżowej szkole I stopnia" ) {
    cat0("### Uzyskiwanie świadectwa dojrzałości - absolwenci ", obiekt$typ_szk2_dop2," z 2022 r. {-}  \n\n",
    
        "Absolwenci ", obiekt$typ_szk2_dop2," nie mogą zdobywać tego typu dyplomów.")
}

if (obiekt$typ_szk2 %in% "Liceum ogólnokształcące" |
      obiekt$typ_szk2 %in% "Liceum ogólnokształcące dla dorosłych" |
      obiekt$typ_szk2 %in% "Technikum" | obiekt$typ_szk2 %in% "Branżowa szkoła II stopnia" |
      obiekt$typ_szk2 %in% "Bednarska Szkoła Realna") {
  
  cat0("## Uzyskiwanie świadectwa dojrzałości - absolwenci ", obiekt$typ_szk2_dop2," z 2022 r. {-}  \n\n")
}

if (obiekt$typ_szk2 %in% "Liceum ogólnokształcące" |
      obiekt$typ_szk2 %in% "Liceum ogólnokształcące dla dorosłych" |
      obiekt$typ_szk2 %in% "Technikum" | obiekt$typ_szk2 %in% "Branżowa szkoła II stopnia" |
      obiekt$typ_szk2 %in% "Bednarska Szkoła Realna") {
  cat0("Wykres ", wyk_num(), ": Uzyskiwanie świadectwa dojrzałości - absolwenci ", obiekt$typ_szk2_dop2, " z 2022 r. - ogółem i w podziale na płeć\n\n")


(wykresMaturyPlec %+% 
    dane_wyk_D2_plec(pelna_finalna_ramka_wskaznikow, "Technikum", 2022)) |> # podmiana danych
  zmien_wielkosc_czcionek(baseSize = 16) |> # zmiana wielkości czcionki
  zmien_prog_pokazywania_etykiet(hideBelow = 0.04) |> # zmiana progu ukrywania etykiet
  zmien_rok_w_podpisie(2024)
}
```

```{r '{{analizyPOL[1,]$typ_szk2_skrot[[1]][[j]]}},d2t3'}
if (obiekt$typ_szk2 %in% "Liceum ogólnokształcące" |
      obiekt$typ_szk2 %in% "Liceum ogólnokształcące dla dorosłych" |
      obiekt$typ_szk2 %in% "Technikum" | obiekt$typ_szk2 %in% "Branżowa szkoła II stopnia" |
      obiekt$typ_szk2 %in% "Bednarska Szkoła Realna") {
if (!colnames(dane$d2_22_sex)[1] %in% "Uwaga") {
  cat0("Tabela ", tab_num(), ": Uzyskiwanie świadectwa dojrzałości - absolwenci ", obiekt$typ_szk2_dop2, " z 2022 r. - ogółem i w podziale na płeć\n\n")
  
dane_tab_D2_plec(pelna_finalna_ramka_wskaznikow, "Technikum", 2022) %>% gentab_tab_D(2024)
}
}
```

```{r '{{analizyPOL[1,]$typ_szk2_skrot[[1]][[j]]}},d2w7'}
if (obiekt$typ_szk2 %in% "Technikum" | obiekt$typ_szk2 %in% "Branżowa szkoła II stopnia") {
  cat0("Wykres ", wyk_num(), ": Uzyskiwanie świadectwa dojrzałości - absolwenci ", obiekt$typ_szk2_dop2, " z 2022 r. - w podziale na zawody o największej liczbie absolwentów\n\n")


(wykresMaturyZawod %+% 
    dane_wyk_D2_zaw(pelna_finalna_ramka_wskaznikow, "Technikum", 2022)) |> # podmiana danych
  zmien_wielkosc_czcionek(baseSize = 14) |> # zmiana wielkości czcionki
  zmien_prog_pokazywania_etykiet(hideBelow = 0.04) |> # zmiana progu ukrywania etykiet
  zmien_rok_w_podpisie(2024)
}
```

```{r '{{analizyPOL[1,]$typ_szk2_skrot[[1]][[j]]}},d2t7'}
if (obiekt$typ_szk2 %in% "Technikum" | obiekt$typ_szk2 %in% "Branżowa szkoła II stopnia") {
  cat0("Tabela ", tab_num(), ": Uzyskiwanie świadectwa dojrzałości - absolwenci ", obiekt$typ_szk2_dop2, " z 2022 r. - w podziale na zawody o największej liczbie absolwentów\n\n")
  
dane_tab_D2_zaw(pelna_finalna_ramka_wskaznikow, "Technikum", 2022) %>% gentab_tab_D(2024)
}
```

